// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sayo.proto

#include "sayo.pb.h"
#include "sayo.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sayo {

static const char* SayoService_method_names[] = {
  "/sayo.SayoService/StreamingASR",
};

std::unique_ptr< SayoService::Stub> SayoService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SayoService::Stub> stub(new SayoService::Stub(channel, options));
  return stub;
}

SayoService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamingASR_(SayoService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>* SayoService::Stub::StreamingASRRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::sayo::AudioChunk, ::sayo::ASRResult>::Create(channel_.get(), rpcmethod_StreamingASR_, context);
}

void SayoService::Stub::async::StreamingASR(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sayo::AudioChunk,::sayo::ASRResult>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::sayo::AudioChunk,::sayo::ASRResult>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingASR_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>* SayoService::Stub::AsyncStreamingASRRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::sayo::AudioChunk, ::sayo::ASRResult>::Create(channel_.get(), cq, rpcmethod_StreamingASR_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>* SayoService::Stub::PrepareAsyncStreamingASRRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::sayo::AudioChunk, ::sayo::ASRResult>::Create(channel_.get(), cq, rpcmethod_StreamingASR_, context, false, nullptr);
}

SayoService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SayoService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< SayoService::Service, ::sayo::AudioChunk, ::sayo::ASRResult>(
          [](SayoService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::sayo::ASRResult,
             ::sayo::AudioChunk>* stream) {
               return service->StreamingASR(ctx, stream);
             }, this)));
}

SayoService::Service::~Service() {
}

::grpc::Status SayoService::Service::StreamingASR(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sayo

