// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sayo.proto
#ifndef GRPC_sayo_2eproto__INCLUDED
#define GRPC_sayo_2eproto__INCLUDED

#include "sayo.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sayo {

// gRPC сервис для стримингового ASR
class SayoService final {
 public:
  static constexpr char const* service_full_name() {
    return "sayo.SayoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Клиент шлёт поток AudioChunk, сервер — поток ASRResult
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>> StreamingASR(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>>(StreamingASRRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>> AsyncStreamingASR(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>>(AsyncStreamingASRRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>> PrepareAsyncStreamingASR(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>>(PrepareAsyncStreamingASRRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Клиент шлёт поток AudioChunk, сервер — поток ASRResult
      virtual void StreamingASR(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sayo::AudioChunk,::sayo::ASRResult>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>* StreamingASRRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>* AsyncStreamingASRRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sayo::AudioChunk, ::sayo::ASRResult>* PrepareAsyncStreamingASRRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>> StreamingASR(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>>(StreamingASRRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>> AsyncStreamingASR(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>>(AsyncStreamingASRRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>> PrepareAsyncStreamingASR(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>>(PrepareAsyncStreamingASRRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamingASR(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sayo::AudioChunk,::sayo::ASRResult>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>* StreamingASRRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>* AsyncStreamingASRRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::sayo::AudioChunk, ::sayo::ASRResult>* PrepareAsyncStreamingASRRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamingASR_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Клиент шлёт поток AudioChunk, сервер — поток ASRResult
    virtual ::grpc::Status StreamingASR(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamingASR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamingASR() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamingASR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingASR(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingASR(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamingASR<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamingASR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamingASR() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::sayo::AudioChunk, ::sayo::ASRResult>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingASR(context); }));
    }
    ~WithCallbackMethod_StreamingASR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingASR(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::sayo::AudioChunk, ::sayo::ASRResult>* StreamingASR(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StreamingASR<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamingASR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamingASR() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamingASR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingASR(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamingASR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamingASR() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamingASR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingASR(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingASR(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamingASR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamingASR() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingASR(context); }));
    }
    ~WithRawCallbackMethod_StreamingASR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingASR(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sayo::ASRResult, ::sayo::AudioChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingASR(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace sayo


#endif  // GRPC_sayo_2eproto__INCLUDED
